development:
  adapter: postgresql
  encoding: unicode
  database: high-priest_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: high-priest_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: high-priest_production
  host: localhost
  pool: 5
  username: postgres
  password: postgres
